# Generated by Django 3.2.8 on 2021-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_leavedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedate',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
