# Generated by Django 3.2.9 on 2021-11-11 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_leavedate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedate',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavedate',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
