# Generated by Django 3.2.9 on 2021-11-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedate',
            name='comments',
            field=models.TextField(),
        ),
    ]
